name: PhantomJS 2.1.1 Build
on:
  push:
    paths:
      - .trigger
      - phantomjs/**
      - .github/workflows/*phantomjs*

jobs:
  phantomjs:
    name: PhantomJS 2.1.1 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v2
        with:
          context: ./phantomjs
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/rollupdev/phantomjs:2.1.1
            docker.io/rollupdev/phantomjs:latest
